AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  pdf

Globals:
  Function:
    Timeout: 30

    LoggingConfig:
      LogFormat: JSON

Resources:
  AWSTemplateFormatVersion: 2010-09-09
Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      AccessControl: Private
      BucketName: nadtakan-s3-pdf-test

  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello-world/
      Handler: app.handler
      Runtime: nodejs18.x
      MemorySize: 10240
      FunctionUrlConfig:
        AuthType: NONE
      Architectures:
      - x86_64
      Policies:
        - AWSLambdaExecute
        - Version: '2012-10-17' 
          Statement:
            - Effect: Allow
              Action:
                - s3:PutObject
              Resource: 'arn:aws:s3:::nadtakan-s3-pdf-test/*'
